name: Build Cross-Platform Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}  # Allows manual trigger via GitHub UI

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows executable with PyInstaller
        run: |
          pyinstaller --onefile --add-data "sounds/*;sounds" jedi.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/app.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS app with PyInstaller
        run: |
          pyinstaller --onefile --add-data "sounds/*:sounds" jedi.py

      - name: Upload macOS app
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/app

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux executable with PyInstaller
        run: |
          pyinstaller --onefile --add-data "sounds/*:sounds" jedi.py

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: dist/app
